### ISSUE TITLE
Fix incompatibility with IDE builds 242.* or higher (2024.3)

### ISSUE THREAD

**Issue by rubin55** [rockofox/intellij-haskell-lsp#10]
The plugin fails to load on latest JetBrains IDEs.

**Comment by rockofox** [comment]
It seems to work fine for me on `IntelliJ IDEA 2024.3 (Ultimate Edition)
Build #IU-243.21565.193`. Is there any error message?

**Comment by rubin55** [comment]
Thid is in CLion 2024.3:
![image](https://github.com/user-attachments/assets/ab9ef6bb-266e-4eb9-887d-998e13ec3efc)

**Comment by rockofox** [comment]
Hmm, interesting. 1.2.1 is the last version that didn't use LSP4IJ. That should work with other IDEs too, though. 

But I can see now on the JetBrains Marketplace that there's an issue with compatibility on other IDEs, so I'll continue investigating.

![grafik](https://github.com/user-attachments/assets/b326d43f-e1ac-414b-bc0e-3ae803fc724f)

**Comment by wizzard0** [comment]
Reproduces with Webstorm and PyCharm 2024.3

**Comment by rockofox** [comment]
Should be fixed now in 1.3.5. It could take bit until it gets approved on the marketplace, I set up a Github release so you can download it from here in the meantime: https://github.com/rockofox/intellij-haskell-lsp/releases/tag/1.3.5

Feel free to reopen if the issue persists ^^
