### ISSUE TITLE
GHCup version of haskell-language-server doesn't work

### ISSUE THREAD

**Issue by 6im0n** [rockofox/intellij-haskell-lsp#2]
**🐛 Describe the bug**
Problem when using the plugin in intellij IDE

**👀 To Reproduce**
1. Go to intellij
2. Open a haskell project
3. Haskell LSP display an error 

**🤷 Expected behavior**
No error

**📸 Screenshots**
![image](https://github.com/rockofox/intellij-haskell-lsp/assets/46846093/1e5e9d28-73c9-457e-9bb0-faefe166fc63)

**💻 Desktop (please complete the following information):**
 - OS: [e.g. Linux, Fedora ]

**Additional context**
I have installed the lastet version of haskell GHCUP, HSL and stack

**Comment by rockofox** [comment]
I'm pretty sure I've found and fixed the issue.
I've published a new version to the JetBrains Marketplace, until that gets approved you can download the new version here: https://github.com/rockofox/intellij-haskell-lsp/releases/tag/1.2.1

Please reopen if it still doesn't work properly.

**Comment by jamesrweb** [comment]
I am using `1.2.1` and get the same issue right now. Can you re-open and investigate?

**Comment by rockofox** [comment]
@jamesrweb Do you have [haskell-language-server](https://haskell-language-server.readthedocs.io/en/latest/installation.html) installed on your machine? Are there any errors?

**Comment by jamesrweb** [comment]
I investigated and it seems to be a problem with the `ghcup` version of the LSP. When running that, the plugin throws this error.

When using the `brew` version, the plugin works fine.

I am assuming this is NOT the plugins issue with that being the case and IS a problem of the `ghcup` version.

**Comment by infloop** [comment]
Hey-hey, could you describe what is the issue with `ghcup` version of the LSP?

**Comment by jamesrweb** [comment]
I have no idea 🤷🏻‍♂️. I just know that when I install it with `brew` it works and when I used `ghcup` it didn't.

**Comment by rockofox** [comment]
@sumanthegde @develmac Please try the new release. It should work with ghcup-installed language server as well.
It's probably not available on marketplace yet, so I've put up a release [here](https://github.com/rockofox/intellij-haskell-lsp/releases/tag/1.3.1).

**Comment by sumanthegde** [comment]
Tried 1.3.1, got this notification: "Haskell Language Server not found. Make sure it is installed properly (and is available in PATH or via ghcup), and restart the IDE." As far as I see, `~/.ghcup/bin` is in `PATH`.

**Comment by rockofox** [comment]
@sumanthegde 
I've redone a bunch of logic and properly tested it with a clean GHCup installation this time, and it should work now.

I've pushed a new version (1.3.2) to marketplace (awaiting review) and to a [github release](https://github.com/rockofox/intellij-haskell-lsp/releases/tag/1.3.2)

**Comment by sumanthegde** [comment]
It's able to connect to HLS now. Thank you!

**Comment by rockofox** [comment]
Great to hear!
I'll close this issue now, as the problem seems to be solved.
Feel free to reach out again if any problems, old or new, arise ^^

**Comment by develmac** [comment]
@rockofox not sure why my previous comment is gone, but anyway I also tested it and now it works great! Just amazing, I have been waiting for something like this for years, thank you so much!
